version: "3.8"
services:
  server:
    image: "svm-server"
    build:
      context: .
    container_name: "svm-server"
    restart: always
    volumes:
      - /var/svm/bin:/app/bin
      - /var/svm/kv:/app/kv
